### ISSUE TITLE
CH to cluster member communication

### ISSUE THREAD

**Issue by eastblue1** [Agr-IoT/LEACH#1]
What module deals with the CH to normal nodes (NCH/clustermember) communication.

The regular LEACH uses TDMA for CH to cluster member communication. Is there a way to change that within this project.

**Comment by n-jay** [comment]
This implementation of LEACH runs on the IEEE 802.15.4 standard which is entirely based on CSMA. 
So this uses CSMA throughout as well.
I will mention that in the README.

**Comment by abdoul-aziz** [comment]
I try to run the code by following the instruction without success. Here the error I got. [Error reuslting ](https://stackoverflow.com/questions/74244549/omnetpp-and-inet-4-run-leach-protcole)

Thanks for any help.

**Comment by n-jay** [comment]
Hi @abdoul-aziz can you create a new issue for this since this is not related to this issue topic?

**Comment by abdoul-aziz** [comment]
> Hi @abdoul-aziz can you create a new issue for this since this is not related to this issue topic?

OK.
