### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by Rahi63** [Agr-IoT/LEACH#11]
Hello,
First of all, thank you for making this code available to download. I am new to Omnet++, and I am trying to create my own network. According to the given instructions, I imported this project, but there is an error during execution that I don't know how to fix. Can you please help me?

![1](https://user-images.githubusercontent.com/36030289/226602716-a469fa44-c3c0-476c-86f4-19a320a6c9d2.png)

**Comment by Rahi63** [comment]
![image](https://user-images.githubusercontent.com/36030289/226607221-00dc284b-b013-4a66-bf15-ba49de61ae90.png)

**Comment by n-jay** [comment]
@Rahi63, sorry for the late reply, did you manage to resolve this?
It seems there might be an issue with the INET or OMNET version you're using.

**Comment by Rahi63** [comment]
Hello Nuwan,
Thank you for your reply. Unfortunately, I couldn't execute your code. In
fact, I am new to omnet++, but I am really eager to learn and work with it.
I have read some tutorial documents, but for creating source, message, and
header files, I have problems. Is it possible to guide me on how to
practice and learn this simulation framework?

Thank you,
Raheleh

**Comment by n-jay** [comment]
Hi @Rahi63,
I'm not sure which parts of the code you're having trouble with. If you were more descriptive I might be able to be of assistance.
