### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Infinite-Blue** [Agr-IoT/LEACH#12]
Hello, I ran into some issues while debugging your code. I would appreciate it if you could help me with some answers.
<img width="860" alt="4 17" src="https://user-images.githubusercontent.com/66893664/232516703-75a14d73-1762-4009-834d-65bffe7746da.png">
thank you.

**Comment by Infinite-Blue** [comment]
Version 6.0.1, inet4.2.10

**Comment by n-jay** [comment]
> Version 6.0.1, inet4.2.10

I've specified in the README that I've only tested the code on OMNeT++ version 5.6.2 and INET Framework version 4.2.5.
I haven't been able to check for version 6 and different INET versions so can't guarantee compatibility.
