### ISSUE TITLE
There was a problem rebuilding inet

### ISSUE THREAD

**Issue by Lark-Ding** [Agr-IoT/LEACH#14]
Hello, I reported an error after I put the code in leach into inet and rebuilt inet. My version has been confirmed that there is no problem. Could you help me see how to solve it?
![image](https://github.com/Agr-IoT/LEACH/assets/117901176/84002c1f-3b2f-46b7-8462-fdc1ebda574a)
![image](https://github.com/Agr-IoT/LEACH/assets/117901176/52e26dfc-233b-445b-8c60-d87c4427efae)
![image](https://github.com/Agr-IoT/LEACH/assets/117901176/e0c92842-62c3-4430-baed-5aaec9fbdb19)
![image](https://github.com/Agr-IoT/LEACH/assets/117901176/a8bb5bf6-fb80-484a-91f3-9a7455a0503a)

**Comment by nassssro0444** [comment]
@Lark-Ding did you find any solution

**Comment by n-jay** [comment]
@Lark-Ding I have not tested this with windows so can't say for certain if its based on that.
could you share a screenshot of what the error message is?
