### ISSUE TITLE
Build error when installing LEACH3 project

### ISSUE THREAD

**Issue by abdoul-aziz** [Agr-IoT/LEACH#2]
I try to run the code by following the instruction without success. Here the error I got. [Error reuslting](https://stackoverflow.com/questions/74244549/omnetpp-and-inet-4-run-leach-protcole)

Thanks for any help.

**Comment by n-jay** [comment]
Hi @abdoul-aziz 
I've commented on your StackOverflow [question](https://stackoverflow.com/questions/74244549/omnetpp-and-inet-4-run-leach-protcole).

**Comment by pjake12** [comment]
Hello @n-jay 

How do you rebuild the project after linking it to the INET directory?

Thank you!

**Comment by n-jay** [comment]
1. Open LEACH3 project on the explorer pane (on the left side) 
2. Click on `project > build project` in the top menu to build that specific project.
Alternatively,` Ctrl+B `will build both INET and the LEACH3 projects together

**Comment by abdoul-aziz** [comment]
Hello @n-jay !  Hope your are Good. So I got a new error. 

```
Error: Cannot load library 'libLEACH3.so': libLEACH3.so: cannot open shared object file: No such file or directory

End.
```
Thanks for any help or suggestions

**Comment by n-jay** [comment]
You hadn't left any updates on whether your previous error got resolved after my advice either here or on StackOverflow.
Please be mindful and make sure you leave such updates as it helps the community.

And please follow my earlier instructions and **create a fresh issue instead of replying to a closed issue**

**Comment by abdoul-aziz** [comment]
> 1. Open LEACH3 project on the explorer pane (on the left side)
> 
>     2. Click on `project > build project` in the top menu to build that specific project.
>        Alternatively,`Ctrl+B`will build both INET and the LEACH3 projects together

Thanks, @Nuwan Jayawardene, this problem is solved by following your instructions. 
Actually, I got another error.
