### ISSUE TITLE
Make nodes send data

### ISSUE THREAD

**Issue by RomainBerthomieu** [Agr-IoT/LEACH#4]
Hello,

Launching the omnetpp.ini does give me a network, but the nodes do not send data to the BS. How can I get the nodes to actually send data?

**Comment by n-jay** [comment]
@RomainBerthomieu, [this method](https://github.com/Agr-IoT/LEACH/blob/dfcd026e550ff07ca7862a016fc11754f34af84b/inet/routing/leach/Leach.cc#L299) in Leach.cc file sends a packet to the BS, however, there is no actual sensor data being sent.

What you can do is amend the [LeachPkts.msg](https://github.com/Agr-IoT/LEACH/blob/main/inet/routing/leach/LeachPkts.msg) file to include a data field and amend the code to populate it with some randomized sensor data to simulate a sensor reading being sent to the BS.
