### ISSUE TITLE
Class "inet::Leach" not found

### ISSUE THREAD

**Issue by rana97ahmad** [Agr-IoT/LEACH#6]
Hello, 
Thank you so much for this leach implementation. 
When I try to run the code with the simulator I get a Class inet::Leach not found error
I am a beginner in Omnet and don't know how to fix this error 
![leachError](https://user-images.githubusercontent.com/44316352/205381251-500c45f0-0498-4f85-ac0f-ca6d6566487f.PNG)

**Comment by n-jay** [comment]
Hi Rana, what version of INET and OMNETPP are you using?
