### ISSUE TITLE
Error when rebuilding INET

### ISSUE THREAD

**Issue by pjake12** [Agr-IoT/LEACH#7]
I encountered an error when rebuilding INET
![error](https://user-images.githubusercontent.com/117272839/205487763-b709910d-f422-45f0-ba6a-21ee06237c55.PNG)

**Comment by pjake12** [comment]
![error 1](https://user-images.githubusercontent.com/117272839/205489476-dbf48ef1-de27-4285-9075-5acacd6e33b6.PNG)

This is the error when I tried to run the project

**Comment by abdoul-aziz** [comment]
> ![error 1](https://user-images.githubusercontent.com/117272839/205489476-dbf48ef1-de27-4285-9075-5acacd6e33b6.PNG)
> 
> This is the error when I tried to run the project

Hi @pjake12, I got the same error solve it by disable clang and enable gcc in configure.user file. to do that:
1. open configure.user file with notepad oe anything else
2. uncomment  gcc by removing # at the begining of the line
3. change the option yes for clang to no like this => PREFER_CLANG=no
4. close and run the commande ./configure to set the new configuration option 
5. and make to compile. 



 you did it just switch in another workspace and

**Comment by n-jay** [comment]
@pjake12, commit https://github.com/Agr-IoT/LEACH/commit/83508d433a0ec641e3176e63951148d0a15276d3 will resolve https://github.com/Agr-IoT/LEACH/issues/7#issue-1474727239.

Hope you managed to resolve https://github.com/Agr-IoT/LEACH/issues/7#issuecomment-1336395828. 
@abdoul-aziz has also provided some steps for a possible resolution.

Please consider updating this thread with your progress and close it if you successfully resolved it.

**Comment by pjake12** [comment]
![error 2](https://user-images.githubusercontent.com/117272839/206881586-dd093491-8b52-472d-8eaa-04413ab5aacb.PNG)

Thank you it has solved the errors however a new error has occurred after I stated the nominal capacities of each nodes as seen on the image attached.

**Comment by pjake12** [comment]
![error 3](https://user-images.githubusercontent.com/117272839/206881746-91d25297-63ac-441a-8029-b5aa807b7162.PNG)
This is the error when I set the nominal capacities at 0.5 J and the previous comment is for the error when I set the nominal capacity to 0J which was the default that was in the text box.

**Comment by n-jay** [comment]
@pjake12 please create a new issue for https://github.com/Agr-IoT/LEACH/issues/7#issuecomment-1345424668 and https://github.com/Agr-IoT/LEACH/issues/7#issuecomment-1345425547.
I will be closing this thread as initial issue was resolved
