### ISSUE TITLE
Error after setting nominal capacity

### ISSUE THREAD

**Issue by pjake12** [Agr-IoT/LEACH#8]
![error 2](https://user-images.githubusercontent.com/117272839/206887084-09e5adff-203a-451b-bdf4-a28e6abbe4f0.PNG)
I get this error after setting nominal capacity of nodes to 0.1J

![error 3](https://user-images.githubusercontent.com/117272839/206887099-04b3ad37-c0b4-42ef-8600-3b87f3a72ad7.PNG)
I get this error after setting nominal capacity of nodes to 0.5J

**Comment by n-jay** [comment]
> I get this error after setting nominal capacity of nodes to 0.1J

I feel like the energy in the node is not sufficient to run the nodes resulting in the crash.
You can perhaps remove the `sim-time-limit` and see if it makes a difference

> I get this error after setting nominal capacity of nodes to 0.5J

I've tested this on 0.5J but was unable to reproduce this error.
Need further info about your setup.

Please update this thread if you made any progress with a resolution

**Comment by pjake12** [comment]
Hello @n-jay 

It seems to work only when nominal capacity is at 1J. I tried it at 5J and 10J but it just ends the simulation immediately. I also get this error whenever I try to rebuild the circuit.

 
![error 4](https://user-images.githubusercontent.com/117272839/207597758-69d996b1-b6e1-4277-8012-c69c4976a091.PNG)

Also here are my other questions about this simulation:

What is the difference of nominal capacity and initial capacity?
Are the nodes and base station placed on random locations?
Why doesn't the LEACH simulation change cluster heads after the current cluster head is done sending the packets to the base station? How much time does one round take before the simulation changes cluster heads?

**Comment by n-jay** [comment]
> It seems to work only when nominal capacity is at 1J. I tried it at 5J and 10J but it just ends the simulation immediately. I also get this error whenever I try to rebuild the circuit.

I cannot recreate this issue without knowing what changes have been done to your specific simulation.
Might I suggest removing this line as I encountered something similar during development: 
https://github.com/Agr-IoT/LEACH/blob/67f65a670de7475fef146002a2172bf0295deaa0/LEACH3/omnetpp.ini#L63

> What is the difference of nominal capacity and initial capacity?

Please refer [INET documentation](https://doc.omnetpp.org/inet/api-current/neddoc/inet.power.storage.SimpleEpEnergyStorage.html). 
Tool tips when hovering over parameters in ini file also help

![Selection_504](https://user-images.githubusercontent.com/24616975/207762553-2192b2e4-c85a-47f0-9f93-2319015b389c.png)

> Are the nodes and base station placed on random locations?

Yes, depending on number of nodes set they are placed randomly.
Please refer [INET documentation](https://inet.omnetpp.org/docs/users-guide/ch-mobility.html). 

> Why doesn't the LEACH simulation change cluster heads after the current cluster head is done sending the packets to the base station?

It does. Once all queued messages are sent to BS, it removes itself as a CH.
Next, CH is elected based on LEACH algorithm.

> How much time does one round take before the simulation changes cluster heads?

There is no pre-determined time. Once a CH is finished sending data to BS, it removes itself as a CH.
