### ISSUE TITLE
Node placement not random 

### ISSUE THREAD

**Issue by pjake12** [Agr-IoT/LEACH#9]
![placement](https://user-images.githubusercontent.com/117272839/212624083-1b7bc94b-dfb5-4e65-81dd-4742ee0a0f99.PNG)

when running the simulation, the node placements are constantly positioned like this. How can I make the placements random?

**Comment by n-jay** [comment]
If you're using the `StationaryMobility` module, then nodes are indeed placed randomly but deterministically. Meaning that the positioning does not change.
I believe this can be changed by passing the seed value in the .ini file.

I recommend you looking into the Mobility model doc for further details.
https://inet.omnetpp.org/docs/users-guide/ch-mobility.html#stationary
